services:
  app:
    build: .
    container_name: code-generator-app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  frontend:
    build:
      context: ./app/frontend
    container_name: code-generator-frontend
    ports:
      - "8501:8501"
    volumes:
      - ./app/frontend:/app
    depends_on:
      - app
    environment:
      - APP_URL=http://app:8000/api
      - ZIP_URL=http://localhost:8000/api/download/project.zip
      - MAX_IMAGE_SIZE_MB=4
